[tool.ruff]
show-fixes = true
line-length = 120
ignore = ["E501"]

[tool.ruff.lint]
extend-select = [
    "B",
    "BLE",
    "C4",
    "COM",
    # "CPY",
    "E",
    # "ERA",
    "FBT",
    "FLY",
    "G",
    "I",
    "ICN",
    # "INP",
    "ISC",
    "LOG",
    "N",
    "NPY",
    "PERF",
    "PGH",
    "PIE",
    # "PTH",
    "PYI",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TCH",
    "TID",
    "UP",
    "YTT",
]